### ISSUE TITLE
German sources

### ISSUE THREAD

**Issue by tuttle** [Markismus/Hogwarts-Legacy-Dutch-text#3]
Hi, may ask a big favor of you? Could you please provide the German JSON source files? I would like to translate the texts into Czech and make them available to my wife and son, for whom English is a barrier.

We have the PS4 version, which probably can't be patched, but having a list of texts next to player will help I think. Thanks in advance for your consideration and help!

**Comment by Markismus** [comment]
In the readme there is a large piece of text reproduced from the internet with an accompanying link to it. 
There it is explained how you can extract and repackage the JSON files. Without repackaging the game won't be able to use your translated files.
